destinations=['my bed','arby','new york','japan','the moon']
print(destinations)
print(sorted(destinations))
print(destinations)
print(sorted(destinations,reverse=True))
print(destinations)
destinations.reverse()
print(destinations)
destinations.reverse()
print(destinations)
destinations.sort()
print(destinations)
destinations.sort(reverse=True)
print(destinations)
